/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as erc1967 from "./ERC1967";
import type * as beacon from "./beacon";
import type * as transparent from "./transparent";

export type { erc1967 };

export type { beacon };

export type { transparent };
export type { Proxy } from "./Proxy";
