@startuml
participant Moderator
box #F0F8FF
participant PookyMintEvent
participant PookyballMinter
end box

Moderator -> PookyballMinter : setVrfParameters

Moderator -> PookyballMinter: createMintTemplate(rarity)
activate PookyballMinter
PookyballMinter --> Moderator: templateId
deactivate PookyballMinter
@enduml
