@startuml
participant User
participant AppBackend
box #F0F8FF
participant PookyMintEvent
participant PookyballMinter
end box
participant Pookyball
participant ChainlinkVRF

User -> AppBackend : pays with credit card

group User Transaction
  AppBackend -> PookyMintEvent : mintBallsAuthorized\n(userAddress, templateId, numberOfBalls)
  group loop [numberOfBalls times]
    PookyMintEvent -> PookyballMinter : _requestMintFromTemplate\n(templateId)
    PookyballMinter -> Pookyball : mintBall
    Pookyball --> PookyballMinter : ball minted
    PookyballMinter -> ChainlinkVRF : requestRandomWords
  end
end

group Chainlink Callback Transaction
  ChainlinkVRF -> PookyballMinter : fulfillRandomWords
  PookyballMinter -> Pookyball : setRandomEntropy
  PookyballMinter -> User : transfer ball
end

group#Pink #Pink Payment dispute
    User <-> AppBackend: Payment disputed
    AppBackend -> PookyMintEvent: revokeBallAuthorized
    PookyMintEvent -> Pookyball: revokeBall
    Pookyball <--> User: ball burned
end

@enduml
