@startuml

object ERC20
object POK {
   transferEnabled
==
  # mint() : PC
  # setTransferEnabled() : ADMIN
}

ERC20 *-- POK

struct BallInfo {
  rarity
  randomEntropy
  level
  pxp
  revokableUntilTimestamp
}

object ERC721

object Pookyball {
  + map balls
==
  + getBallInfo()
  + getBallPxp()
..
  # addBallPxp() : PC
  # changeBallLevel() : PC
  # mintWithRarityAndRevokableTimestamp() : PC
  # revokeBall() : PC
  # setRandomEntropy() : PC
}
ERC721 *-- Pookyball
"Pookyball::map balls" -> BallInfo

struct MintTemplate {
  canMint
  rarity
  maxMints
  currentMints
  price
  payingToken
}

object PookyballMinter {
  + map mintTemplates
==
  #createMintTemplate() : MOD
  # changeMintTemplateCanMint() : MOD
..
  # rawFulfillRandomWords() : CL
..
  ~ _requestMintFromTemplate()
}

"PookyballMinter::map mintTemplates" -> MintTemplate

object PookyMintEvent {
  + mintBalls()
..
  # mintBallsAuthorized() : BE
  # revokeBallAuthorized() : BE
..
  # setAddressTier() : MOD
  # setMinTierToBuy() : MOD
}

object PookyMarketplace {
  TBD
}


PookyballMinter *-- PookyMintEvent
PookyballMinter *-- PookyMarketplace

object PookyGame {
  + matchweekClaim()
  + levelUp()
}

object Legend #LightBlue {
  + public function
  # authorized function
  ~ internal function
}

object Roles #LightGreen {
  PC - Pooky Contract
  ADMIN - Important admin
  MOD - Moderator
  BE - Backend wallet
  CL - Chainlink
}

Legend -[hidden]-> Roles
POK -[hidden]> Pookyball
Pookyball -[hidden]-> PookyballMinter
POK -[hidden]-> PookyGame

@enduml
