/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  InvalidReceiver,
  InvalidReceiverInterface,
} from "../../../contracts/testing/InvalidReceiver";

const _abi = [
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b50605d80601d6000396000f3fe608060405236601f57601a673d8f2127a535885760c01b6024565b600080fd5b600080fd5b5056fea2646970667358221220636667d422a8918bc5ceefb57a7f9d777ca0ed92615fbd170b595f92fc1bb49564736f6c63430008110033";

type InvalidReceiverConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: InvalidReceiverConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class InvalidReceiver__factory extends ContractFactory {
  constructor(...args: InvalidReceiverConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<InvalidReceiver> {
    return super.deploy(overrides || {}) as Promise<InvalidReceiver>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): InvalidReceiver {
    return super.attach(address) as InvalidReceiver;
  }
  override connect(signer: Signer): InvalidReceiver__factory {
    return super.connect(signer) as InvalidReceiver__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): InvalidReceiverInterface {
    return new utils.Interface(_abi) as InvalidReceiverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): InvalidReceiver {
    return new Contract(address, _abi, signerOrProvider) as InvalidReceiver;
  }
}
